channels:
  - defaults
dependencies:
  - python=3.12
  - pip
  - pip:
      - pandas
      - scikit-learn
      - mlflow
      - prometheus-client
      - fastapi
      - joblib
      - uvicorn
      - prometheus-client
      - tqdm
